
import { AiFillStar } from "react-icons/ai";

// navbar bottom product list
export const navBarBottomList = [
  {
    _id: 1001,
    image: "https://rukminim1.flixcart.com/flap/96/96/image/29327f40e9c4d26b.png?q=100",
    name: "Grocery",
  },
  {
    _id: 1002,
    image: "https://rukminim1.flixcart.com/flap/96/96/image/22fddf3c7da4c4f4.png?q=100",
    name: "Mobiles",
  },
  {
    _id: 1003,
    image: "https://rukminim1.flixcart.com/fk-p-flap/96/96/image/0d75b34f7d8fbcb3.png?q=100",
    name: "Fashion",
  },
  {
    _id: 1004,
    image: "https://rukminim1.flixcart.com/flap/96/96/image/69c6589653afdb9a.png?q=100",
    name: "Electronics",
  },
  {
    _id: 1005,
    image: "https://rukminim1.flixcart.com/flap/96/96/image/ab7e2b022a4587dd.jpg?q=100",
    name: "Home Furniture",
  },
  {
    _id: 1006,
    image: "https://rukminim1.flixcart.com/flap/96/96/image/0ff199d1bd27eb98.png?q=100",
    name: "Appliances",
  },
  {
    _id: 1007,
    image: "https://rukminim1.flixcart.com/flap/96/96/image/dff3f7adcf3a90c6.png?q=100",
    name: "Toys and More",
  },
  {
    _id: 1008,
    image: "https://rukminim1.flixcart.com/fk-p-flap/96/96/image/05d708653beff580.png?q=100",
    name: "Bikes",
  },
];
// carousel images
export const carousalItem = [
  {
    _id: 101,
    image:"https://images-eu.ssl-images-amazon.com/images/G/31/img21/Wireless/Shreyansh/BAU/Unrexc/D70978891_INWLD_BAU_Unrec_Uber_PC_Hero_3000x1200._CB594707876_.jpg",
  },
  {
    _id: 102,
    image:"https://images-eu.ssl-images-amazon.com/images/G/31/img2020/img21/apparelGW/julyatf23/unrec/apay/MA_3000._CB600347170_.jpg",
  },
  {
    _id: 104,
    image:"https://images-eu.ssl-images-amazon.com/images/G/31/IMG20/Home/2023/BAU2023/ATFGW/Home_mela_july_3000x1200._CB598959250_.jpg",
  },
  {
    _id: 105,
    image: "https://images-eu.ssl-images-amazon.com/images/G/31/img23/Softlines_JWL_SH_GW_Assets/UNREC/CAT_PC-2_3000._CB598786201_.jpg",
  },
  {
    _id: 106,
    image: "https://m.media-amazon.com/images/I/61aURrton0L._SX3000_.jpg",
  },
 
];
// data for home page
export const newArrivals = [
  {
    _id: 1111,
    img: "https://images.meesho.com/images/products/121005771/l8fvc_512.webp",
    productName: "Water bottle",
    color: "Black",
    price: "15",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",

  },
  {
    _id: 1112,
    img: "https://images.meesho.com/images/products/179415901/4qeq3_512.webp",
    productName: "Bag",
    color: "Red",
    price: "18",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",

  },
  {
    _id: 1113,
    img: "https://images.meesho.com/images/products/225305878/gp26g_512.webp",
    productName: "Wall hanging",
    color: "White",
    price: "10",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",

  },
  {
    _id: 1114,
    img: "https://images.meesho.com/images/products/254697454/98tzx_512.webp",
    productName: "Watch",
    color: "Black",
    price: "18",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",

  },
  {
    _id: 1115,
    img: "https://images.meesho.com/images/products/75970557/6kmep_512.webp",
    productName: "T-shirt",
    color: "Blue",
    price: "25",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",

  },
  {
    _id: 1116,
    img: "https://images.meesho.com/images/products/9873168/b6f05_512.webp",
    productName: "Bathroom tap",
    color: "Metalick",
    price: "7",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",

  },
  {
    _id: 1117,
    img: "https://images.meesho.com/images/products/302151662/o3drd_512.webp",
    productName: "Men shirt",
    color: "Blue Cheak",
    price: "22",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",

  },

];
// special offer data

export const SplOfferData = [
  {
    _id: "201",
    img: "https://m.media-amazon.com/images/I/61LO6l4zB4L._UX522_.jpg",
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "202",
    img: "https://m.media-amazon.com/images/I/81MZRUuHJIL._SL1500_.jpg",
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "203",
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "204",
    img: "https://m.media-amazon.com/images/I/81nj6IlZpVL._UY500_.jpg",
    productName: "Watch",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];

// Best seller
export const BestSellersData = [
  {
    _id: 1181,
    img: "https://m.media-amazon.com/images/I/81itQPVn-GL._SL1500_.jpg",
    productName: "Redmi 12",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "35.00",
    company: "Nike",
    color: "white",
    category: "footwear",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1182,
    img: "https://m.media-amazon.com/images/I/81MZRUuHJIL._SL1500_.jpg",
    productName: "samsung pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "180.00",
    company: "Banntle",
    color: "Gray",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },

  {
    _id: 1184,
    img: "https://m.media-amazon.com/images/I/61LO6l4zB4L._UX522_.jpg",
    productName: "Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "220.00",
    company: "Lovis Davin",
    color: "black",
    category: "watch",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1185,
    img: "https://images.meesho.com/images/products/254697454/98tzx_512.webp",
    productName: "Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "35.00",
    company: "Davin",
    color: "black",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1186,
    img: "https://m.media-amazon.com/images/I/81SvInWFWWL._SL1500_.jpg",
    productName: "Realme narzo",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "180.00",
    company: "Vans",
    color: "green",
    category: "footwear",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1187,
    img: "https://m.media-amazon.com/images/I/71RtIeN2J4L._SL1500_.jpg",
    productName: "One Plus ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "25.00",
    company: "kavitas",
    color: "green",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },

  {
    _id: 1190,
    img: "https://m.media-amazon.com/images/I/61M0tGMbBPL._SL1200_.jpg",
    productName: "Z6 Light",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "44.00",
    company: "fastrack",
    color: "black",
    category: "watch",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
]
export const SpecialOffersData = [
  {
    _id: 1161,
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    productName: "Men's Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "180.00",
    company: "Banntle",
    color: "Gray",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1162,
    img: "https://m.media-amazon.com/images/I/81Tv57SALWL._UL1500_.jpg",
    productName: "Track Pant",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "25.00",
    company: "Banntle",
    color: "black",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1163,
    img: "https://m.media-amazon.com/images/I/51nUfiMuCLL._UL1000_.jpg",
    productName: "T-shirt Pant",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "35.00",
    company: "Davin",
    color: "black",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1164,
    img: "https://m.media-amazon.com/images/I/418Uu3TxxPL.jpg",
    productName: "Printed shirt for men",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "180.00",
    company: "Vans",
    color: "green",
    category: "footwear",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1165,
    img: "https://m.media-amazon.com/images/I/51lKEJm9qFL._UL1100_.jpg",
    productName: "ASIAN Sport shoe ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "25.00",
    company: "kavitas",
    color: "green",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1166,
    img: "https://m.media-amazon.com/images/I/71ShBw4g6GL._UL1500_.jpg",
    productName: "Man-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "220.00",
    company: "kavitas",
    color: "black",
    category: "bag",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1167,
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    productName: "Court Shoes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "44.00",
    company: "fastrack",
    color: "black",
    category: "watch",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1168,
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    productName: "Golf Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "250.00",
    company: "fastrack",
    color: "black",
    category: "watch",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
]

// data for search box filter products
export const paginationItems = [
  {
    _id: 1001,
    img: "https://m.media-amazon.com/images/I/81MZRUuHJIL._SL1500_.jpg",
    productName: "Mobile samsung pro",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1002,
    img: "https://m.media-amazon.com/images/I/81itQPVn-GL._SL1500_.jpg",
    productName: "Redmi 12",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1003,
    img: "https://m.media-amazon.com/images/I/61LO6l4zB4L._UX522_.jpg",
    productName: "Watch",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1004,
    img: "https://m.media-amazon.com/images/I/71ShBw4g6GL._UL1500_.jpg",
    productName: "Man-shirt",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1005,
    img: "https://m.media-amazon.com/images/I/61M0tGMbBPL._SL1200_.jpg",
    productName: "Mobile-Z6 Light",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1006,
    img: "https://m.media-amazon.com/images/I/71B0o+l+-UL._UL1500_.jpg",
    productName: "Sport Shorts",
    price: "180.00",
    color: "Gray",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1007,
    img: "https://m.media-amazon.com/images/I/61kLLOgKixL._SL1500_.jpg",
    productName: "Mixer Grinder",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1008,
    img: "https://m.media-amazon.com/images/I/810s53kR8tL._UL1500_.jpg",
    productName: "Casual Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1009,
    img: "https://m.media-amazon.com/images/I/51Jlp-dxJEL._SL1100_.jpg",
    productName: "Mixer grander",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1010,
    img: "https://images.meesho.com/images/products/179415901/4qeq3_512.webp",
    productName: "Bag",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1011,
    img: "https://m.media-amazon.com/images/I/51nUfiMuCLL._UL1000_.jpg",
    productName: "T-shirt Pant",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1012,
    img: "https://images.meesho.com/images/products/121005771/l8fvc_512.webp",
    productName: " Water bottle",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1013,
    img: "https://m.media-amazon.com/images/I/81itQPVn-GL._SL1500_.jpg",
    productName: " Mobile Redmi 12",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },

  {
    _id: 1014,
    img: "https://images.meesho.com/images/products/254697454/98tzx_512.webp",
    productName: "Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1015,
    img: "https://m.media-amazon.com/images/I/51krmlloEBL._SL1080_.jpg",
    productName: "Lenovo Tab S9",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1016,
    img: "https://m.media-amazon.com/images/I/81bKgIkCjHL._SL1500_.jpg",
    productName: "Water bottele",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1017,
    img: "https://m.media-amazon.com/images/I/71whdzBbJoL._SL1500_.jpg",
    productName: "Asus Laptop",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1018,
    img: "https://m.media-amazon.com/images/I/61nb1cWMOiL._SL1500_.jpg",
    productName: "water bottele",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1019,
    img: "https://m.media-amazon.com/images/I/51W8-7-g58S._SL1500_.jpg",
    productName: "Light bulbs",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1020,
    img: "https://m.media-amazon.com/images/I/61WmkoakULL._SL1080_.jpg",
    productName: "Philips bulbs",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1021,
    img: "https://m.media-amazon.com/images/I/51rEPuvNYFL._SL1080_.jpg",
    productName: "Laptop",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1022,
    img: "https://m.media-amazon.com/images/I/61NzmmNu6nL._UL1300_.jpg",
    productName: "Men-Tshirt",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1023,
    img: "https://m.media-amazon.com/images/I/71SvqTFPXJL._SL1500_.jpg",
    productName: "Xiaomi Tab",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
]