import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";
import { AiFillStar } from "react-icons/ai";

// navbar bottom product list
export const navBarBottomList = [
  {
    _id: 1001,
    image: "https://rukminim1.flixcart.com/flap/96/96/image/29327f40e9c4d26b.png?q=100",
    name: "Grocery",
  },
  {
    _id: 1002,
    image: "https://rukminim1.flixcart.com/flap/96/96/image/22fddf3c7da4c4f4.png?q=100",
    name: "Mobiles",
  },
  {
    _id: 1003,
    image: "https://rukminim1.flixcart.com/fk-p-flap/96/96/image/0d75b34f7d8fbcb3.png?q=100",
    name: "Fashion",
  },
  {
    _id: 1004,
    image: "https://rukminim1.flixcart.com/flap/96/96/image/69c6589653afdb9a.png?q=100",
    name: "Electronics",
  },
  {
    _id: 1005,
    image: "https://rukminim1.flixcart.com/flap/96/96/image/ab7e2b022a4587dd.jpg?q=100",
    name: "Home Furniture",
  },
  {
    _id: 1006,
    image: "https://rukminim1.flixcart.com/flap/96/96/image/0ff199d1bd27eb98.png?q=100",
    name: "Appliances",
  },
  {
    _id: 1007,
    image: "https://rukminim1.flixcart.com/flap/96/96/image/dff3f7adcf3a90c6.png?q=100",
    name: "Toys and More",
  },
  {
    _id: 1008,
    image: "https://rukminim1.flixcart.com/fk-p-flap/96/96/image/05d708653beff580.png?q=100",
    name: "Bikes",
  },
];

export const newArrivals = [
  {
    _id: 1111,
    img: "https://images.meesho.com/images/products/121005771/l8fvc_512.webp",
    productName: "Water bottle",
    color: "Black",
    price: "15",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",

  },
  {
    _id: 1112,
    img: "https://images.meesho.com/images/products/179415901/4qeq3_512.webp",
    productName: "Bag",
    color: "Red",
    price: "18",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",

  },
  {
    _id: 1113,
    img: "https://images.meesho.com/images/products/225305878/gp26g_512.webp",
    productName: "Wall hanging",
    color: "White",
    price: "10",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",

  },
  {
    _id: 1114,
    img: "https://images.meesho.com/images/products/254697454/98tzx_512.webp",
    productName: "Watch",
    color: "Black",
    price: "18",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",

  },
  {
    _id: 1115,
    img: "https://images.meesho.com/images/products/75970557/6kmep_512.webp",
    productName: "T-shirt",
    color: "Blue",
    price: "25",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",

  },
  {
    _id: 1116,
    img: "https://images.meesho.com/images/products/9873168/b6f05_512.webp",
    productName: "Bathroom tap",
    color: "Metalick",
    price: "7",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",

  },
  {
    _id: 1117,
    img: "https://images.meesho.com/images/products/302151662/o3drd_512.webp",
    productName: "Men shirt",
    color: "Blue Cheak",
    price: "22",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",

  },

];
// special offer data

export const SplOfferData = [
  {
    _id: "201",
    img: "https://m.media-amazon.com/images/I/61LO6l4zB4L._UX522_.jpg",
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "202",
    img:"https://m.media-amazon.com/images/I/81MZRUuHJIL._SL1500_.jpg",
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "203",
    img:"https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "204",
    img:"https://m.media-amazon.com/images/I/81nj6IlZpVL._UY500_.jpg",
    productName: "Watch",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];

// Best seller
export const BestSellersData = [
  {
    _id: 1181,
    img: "https://m.media-amazon.com/images/I/81itQPVn-GL._SL1500_.jpg",
    productName: "Redmi 12",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "35.00",
    company: "Nike",
    color: "white",
    category: "footwear",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1182,
    img: "https://m.media-amazon.com/images/I/81MZRUuHJIL._SL1500_.jpg",
    productName: "samsung pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "180.00",
    company: "Banntle",
    color: "Gray",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1183,
    img: spfThree,
    productName: "Headphones",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "25.00",
    company: "Banntle",
    color: "black",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },

  {
    _id: 1184,
    img: "https://m.media-amazon.com/images/I/61LO6l4zB4L._UX522_.jpg",
    productName: "Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "220.00",
    company: "Lovis Davin",
    color: "black",
    category: "watch",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1185,
    img: "https://images.meesho.com/images/products/254697454/98tzx_512.webp",
    productName: "Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "35.00",
    company: "Davin",
    color: "black",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1186,
    img: "https://m.media-amazon.com/images/I/81SvInWFWWL._SL1500_.jpg",
    productName: "Realme narzo",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "180.00",
    company: "Vans",
    color: "green",
    category: "footwear",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
 {
    _id: 1187,
    img: "https://m.media-amazon.com/images/I/71RtIeN2J4L._SL1500_.jpg",
    productName: "One Plus ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "25.00",
    company: "kavitas",
    color: "green",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1188,
    img: bestSellerFour,
    productName: "Travel Bag",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "220.00",
    company: "kavitas",
    color: "black",
    category: "bag",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1190,
    img:"https://m.media-amazon.com/images/I/61M0tGMbBPL._SL1200_.jpg",
    productName: "Z6 Light",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "44.00",
    company: "fastrack",
    color: "black",
    category: "watch",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1191,
    img: newArrTwo,
    productName: "Smart Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "250.00",
    company: "fastrack",
    color: "black",
    category: "watch",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
]
export const SpecialOffersData = [
  {
    _id: 1161,
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    productName: "Men's Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "180.00",
    company: "Banntle",
    color: "Gray",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1162,
    img: "https://m.media-amazon.com/images/I/81Tv57SALWL._UL1500_.jpg",
    productName: "Track Pant",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "25.00",
    company: "Banntle",
    color: "black",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1163,
    img: "https://m.media-amazon.com/images/I/51nUfiMuCLL._UL1000_.jpg",
    productName: "T-shirt Pant",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "35.00",
    company: "Davin",
    color: "black",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1164,
    img:"https://m.media-amazon.com/images/I/418Uu3TxxPL.jpg",
    productName: "Printed shirt for men",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "180.00",
    company: "Vans",
    color: "green",
    category: "footwear",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
 {
    _id: 1165,
    img: "https://m.media-amazon.com/images/I/51lKEJm9qFL._UL1100_.jpg",
    productName: "ASIAN Sport shoe ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "25.00",
    company: "kavitas",
    color: "green",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1166,
    img: "https://m.media-amazon.com/images/I/71ShBw4g6GL._UL1500_.jpg",
    productName: "Man-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "220.00",
    company: "kavitas",
    color: "black",
    category: "bag",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1167,
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    productName: "Court Shoes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "44.00",
    company: "fastrack",
    color: "black",
    category: "watch",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1168,
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    productName: "Golf Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "250.00",
    company: "fastrack",
    color: "black",
    category: "watch",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
]


// pagination data

export const paginationItems = [
  {
    _id: 1001,
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    productName: "Nike Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "35.00",
    company: "Nike",
    color: "white",
    category: "footwear",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "Tea Table",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "180.00",
    company: "Banntle",
    color: "Gray",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "Headphones",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "25.00",
    company: "Banntle",
    color: "black",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },

  {
    _id: 1004,
    img: "https://m.media-amazon.com/images/I/61LO6l4zB4L._UX522_.jpg",
    productName: "Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "220.00",
    company: "Lovis Davin",
    color: "black",
    category: "watch",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Flower Base",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "35.00",
    company: "Davin",
    color: "black",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1006,
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    productName: "Flat Slip On Pumps",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "180.00",
    company: "Vans",
    color: "green",
    category: "footwear",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Household materials",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "25.00",
    company: "kavitas",
    color: "green",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Travel Bag",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "220.00",
    company: "kavitas",
    color: "black",
    category: "bag",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Round Table Clock",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "44.00",
    company: "fastrack",
    color: "black",
    category: "watch",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Smart Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "250.00",
    company: "fastrack",
    color: "black",
    category: "watch",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1011,
    img: "https://m.media-amazon.com/images/I/810s53kR8tL._UL1500_.jpg",
    productName: "Casual Bag",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "80.00",
    company: "skybag",
    color: "Black",
    category: "bag",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1012,
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    productName: "Loafer Flats",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "60.00",
    company: "Nike",
    color: "white",
    category: "footwear",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1013,
    img: "https://images.meesho.com/images/products/179415901/4qeq3_512.webp",
    productName: "Bag",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "60.00",
    company: "Skybag",
    color: "red",
    category: "bag",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1014,
    img: "https://m.media-amazon.com/images/I/51nUfiMuCLL._UL1000_.jpg",
    productName: "T-shirt Pant",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "250.00",
    company: "Denim",
    color: "blue",
    category: "clothes",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1015,
    img: "https://images.meesho.com/images/products/121005771/l8fvc_512.webp",
    productName: " Water bottle",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "18.00",
    company: "milton",
    category: "other",
    color: "Black",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1016,
    img: "https://images.meesho.com/images/products/225305878/gp26g_512.webp",
    productName: "Wall hanging",
    title: "DREAM PAIRS Court Shoes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",

    price: "250.00",
    company: "netbrg",
    color: "white",
    category: "other",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1017,
    img: "https://m.media-amazon.com/images/I/81itQPVn-GL._SL1500_.jpg",
    productName: "Redmi 12",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "12000.00",
    company: "Redmi",
    color: "blue",
    category: "phone",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1018,
    img: "https://images.meesho.com/images/products/254697454/98tzx_512.webp",
    productName: "Watch",
    price: "44.00",
    company: "fastrak",
    color: "black",
    category: "watch",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1019,
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    productName: "Men's Sneaker",
    price: "250.00",
    company: "Adidas",
    color: "blue",
    category: "footwear",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1020,
    img: "https://m.media-amazon.com/images/I/81Tv57SALWL._UL1500_.jpg",
    productName: "Track Pant",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "80.00",
    company: "Blue tyga",
    color: "black",
    category: "clothes",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1021,
    img: "https://m.media-amazon.com/images/I/71ZvGBfwi+L._UL1500_.jpg",
    productName: "Casual Pants",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "25.00",
    company: "Denim",
    color: "black",
    category: "clothes",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1022,
    img: spfFour,
    productName: "Sun glasses",
    star: <AiFillStar className="rating-star" />,
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1023,
    img: "https://m.media-amazon.com/images/I/81MZRUuHJIL._SL1500_.jpg",
    productName: "Smart phone",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "35.00",
    company: "Denim",
    color: "blue",
    category: "phone",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1024,
    img: "https://m.media-amazon.com/images/I/81nj6IlZpVL._UY500_.jpg",
    productName: "Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "35.00",
    company: "Puma",
    color: "white",
    category: "watch",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1025,
    img: "https://m.media-amazon.com/images/I/81SvInWFWWL._SL1500_.jpg",
    productName: "Realme narzo",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "1280.00",
    company: "realme",
    color: "gray",
    category: "phone",
        badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1026,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1027,
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    productName: "Golf Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "220.00",
    company: "Puma",
    color: "green",
    category: "footwear",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1028,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1029,
    img: bestSellerTwo,
    productName: "New Backpack",
    price: "180.00",
    color: "Gray",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1030,
    img: bestSellerThree,
    productName: "Household materials",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1031,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1032,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1033,
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    productName: "High heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "250.00",
    company: "Vans",
    color: "black",
    category: "footwear",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1034,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1035,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1036,
    img: newArrTwo,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1037,
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    productName: "Court Shoes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "60.00",
    company: "Nike",
    color: "red",
    category: "footwear",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1038,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1039,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1040,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1041,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1042,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1043,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1044,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1045,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1046,
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
