import {
    spfOne,
    spfTwo,
    spfThree,
    spfFour,
    bestSellerOne,
    bestSellerTwo,
    bestSellerThree,
    bestSellerFour,
    newArrOne,
    newArrTwo,
    newArrThree,
    newArrFour,
  } from "../../../assets/images/index";
  import { AiFillStar } from "react-icons/ai";


const  Products = [
    {
      _id: 1001,
      img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
      productName: "Shoe",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "35.00",
      company: "Nike",
      color: "white",
      category: "footwear",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1002,
      img: spfTwo,
      productName: "Tea Table",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "180.00",
      company: "Banntle",
      color: "Gray",
      category: "other",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1003,
      img: spfThree,
      productName: "Headphones",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "25.00",
      company: "Banntle",
      color: "black",
      category: "other",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
  
    {
      _id: 1004,
      img: "https://m.media-amazon.com/images/I/61LO6l4zB4L._UX522_.jpg",
      productName: "Watch",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "220.00",
      company: "Lovis Davin",
      color: "black",
      category: "watch",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1005,
      img: bestSellerOne,
      productName: "Flower Base",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "35.00",
      company: "Davin",
      color: "black",
      category: "other",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1006,
      img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
      productName: "Flat Slip On Pumps",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "180.00",
      company: "Vans",
      color: "green",
      category: "footwear",
      badge: false,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1007,
      img: bestSellerThree,
      productName: "Household materials",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "25.00",
      company: "kavitas",
      color: "green",
      category: "other",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1008,
      img: bestSellerFour,
      productName: "Travel Bag",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "220.00",
      company: "kavitas",
      color: "black",
      category: "bag",
      badge: false,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1009,
      img: newArrOne,
      productName: "Round Table Clock",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "44.00",
      company: "fastrack",
      color: "black",
      category: "watch",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1010,
      img: newArrTwo,
      productName: "Smart Watch",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "250.00",
      company: "fastrack",
      color: "black",
      category: "watch",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1011,
      img: "https://m.media-amazon.com/images/I/810s53kR8tL._UL1500_.jpg",
      productName: "Casual Bag",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "80.00",
      company: "skybag",
      color: "Black",
      category: "bag",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1012,
      img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
      productName: "Loafer Flats",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "60.00",
      company: "Nike",
      color: "white",
      category: "footwear",
      badge: false,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1013,
      img: "https://images.meesho.com/images/products/179415901/4qeq3_512.webp",
      productName: "Bag",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "60.00",
      company: "Skybag",
      color: "red",
      category: "bag",
      badge: false,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1014,
      img: "https://m.media-amazon.com/images/I/51nUfiMuCLL._UL1000_.jpg",
      productName: "T-shirt Pant",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "250.00",
      company: "Denim",
      color: "blue",
      category: "clothes",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1015,
      img: "https://images.meesho.com/images/products/121005771/l8fvc_512.webp",
      productName: " Water bottle",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "18.00",
      company: "milton",
      category: "other",
      color: "Black",
      badge: false,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1016,
      img: "https://images.meesho.com/images/products/225305878/gp26g_512.webp",
      productName: "Wall hanging",
      title: "DREAM PAIRS Court Shoes",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
  
      price: "250.00",
      company: "netbrg",
      color: "white",
      category: "other",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1017,
      img: "https://m.media-amazon.com/images/I/81itQPVn-GL._SL1500_.jpg",
      productName: "Redmi 12",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "12000.00",
      company: "Redmi",
      color: "blue",
      category: "phone",
      badge: false,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1018,
      img: "https://images.meesho.com/images/products/254697454/98tzx_512.webp",
      productName: "Watch",
      price: "44.00",
      company: "fastrak",
      color: "black",
      category: "watch",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1019,
      img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
      productName: "Men's Sneaker",
      price: "250.00",
      company: "Adidas",
      color: "blue",
      category: "footwear",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1020,
      img: "https://m.media-amazon.com/images/I/81Tv57SALWL._UL1500_.jpg",
      productName: "Track Pant",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "80.00",
      company: "Blue tyga",
      color: "black",
      category: "clothes",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1021,
      img: "https://m.media-amazon.com/images/I/71ZvGBfwi+L._UL1500_.jpg",
      productName: "Casual Pants",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "25.00",
      company: "Denim",
      color: "black",
      category: "clothes",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1022,
      img: spfFour,
      productName: "Sun glasses",
      star: <AiFillStar className="rating-star" />,
      price: "220.00",
      color: "Black",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1023,
      img: "https://m.media-amazon.com/images/I/81MZRUuHJIL._SL1500_.jpg",
      productName: "Smart phone",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "35.00",
      company: "Denim",
      color: "blue",
      category: "phone",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1024,
      img: "https://m.media-amazon.com/images/I/81nj6IlZpVL._UY500_.jpg",
      productName: "Watch",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "35.00",
      company: "Puma",
      color: "white",
      category: "watch",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1025,
      img: "https://m.media-amazon.com/images/I/81SvInWFWWL._SL1500_.jpg",
      productName: "Realme narzo",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "1280.00",
      company: "realme",
      color: "gray",
      category: "phone",
          badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1026,
      img: spfThree,
      productName: "Headphones",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1027,
      img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
      productName: "Golf Shoe",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "220.00",
      company: "Puma",
      color: "green",
      category: "footwear",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1028,
      img: bestSellerOne,
      productName: "Flower Base",
      price: "35.00",
      color: "Blank and White",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1029,
      img: bestSellerTwo,
      productName: "New Backpack",
      price: "180.00",
      color: "Gray",
      badge: false,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1030,
      img: bestSellerThree,
      productName: "Household materials",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1031,
      img: bestSellerFour,
      productName: "Travel Bag",
      price: "220.00",
      color: "Black",
      badge: false,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1032,
      img: newArrOne,
      productName: "Round Table Clock",
      price: "44.00",
      color: "Black",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1033,
      img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
      productName: "High heel",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "250.00",
      company: "Vans",
      color: "black",
      category: "footwear",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1034,
      img: newArrThree,
      productName: "cloth Basket",
      price: "80.00",
      color: "Mixed",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1035,
      img: newArrFour,
      productName: "Funny toys for babies",
      price: "60.00",
      color: "Mixed",
      badge: false,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1036,
      img: newArrTwo,
      productName: "Funny toys for babies",
      price: "60.00",
      color: "Mixed",
      badge: false,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1037,
      img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
      productName: "Court Shoes",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      price: "60.00",
      company: "Nike",
      color: "red",
      category: "footwear",
      badge: false,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1038,
      img: newArrTwo,
      productName: "Smart Watch",
      price: "250.00",
      color: "Black",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1039,
      img: bestSellerFour,
      productName: "Travel Bag",
      price: "220.00",
      color: "Black",
      badge: false,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1040,
      img: newArrOne,
      productName: "Round Table Clock",
      price: "44.00",
      color: "Black",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1041,
      img: newArrTwo,
      productName: "Smart Watch",
      price: "250.00",
      color: "Black",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1042,
      img: newArrThree,
      productName: "cloth Basket",
      price: "80.00",
      color: "Mixed",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1043,
      img: spfThree,
      productName: "Headphones",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1044,
      img: spfFour,
      productName: "Sun glasses",
      price: "220.00",
      color: "Black",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1045,
      img: bestSellerOne,
      productName: "Flower Base",
      price: "35.00",
      color: "Blank and White",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
    {
      _id: 1046,
      img: spfOne,
      productName: "Cap for Boys",
      price: "35.00",
      color: "Blank and White",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    },
  ];
  export default Products ;